### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by quasiperfect** [phpsa/filament-authentication#10]
hi

could you please some usage examples in the documentation.
 
i understand how to use model policies but how i could protect filament resources that don't have models ?
traing to block access to the route of this package for example https://github.com/z3d0x/filament-logger

sorry if i don't make much sense i'm new to laravel and filament and learning

thanks in advance for your help

**Comment by phpsa** [comment]
Will look at the package, some packages may be different based on the package itself.

**Comment by phpsa** [comment]
seems to implement: `Spatie\Activitylog\Models\Activity` model so you should be able to publish the policy and attach it per:
https://github.com/phpsa/filament-authentication#security

**Comment by quasiperfect** [comment]
thanks
