### ISSUE TITLE
Email confirmation

### ISSUE THREAD

**Issue by dpetrovaliev** [phpsa/filament-authentication#13]
Is there any option to send an email confirmation to the user after creating the account?

**Comment by phpsa** [comment]
We can add some custom events in, Will add this to the feature list and should be out in a few days

**Comment by phpsa** [comment]
Dispatching: `Phpsa\FilamentAuthentication\Events\UserUpdated` & `Phpsa\FilamentAuthentication\Events\UserCreated`
on update and deleted from 2.1.0 -- beta release running for this week

You can now create a listener to dispatch the mail on that event
