### ISSUE TITLE
Double Entry in navigation menu

### ISSUE THREAD

**Issue by ramakrishnamie** [phpsa/filament-authentication#24]
Hello,
After I successfully installed this plugin, It was working fine with default user model. but when I create UserResource again, the double entry is displaying as in screenshot. It may be my fault also. can you please guide me please. I want only one user menu item in the navigation group.
![Screenshot 2022-10-18 182222](https://user-images.githubusercontent.com/82993265/196435693-961d874f-f801-4285-b233-32eda4dfed63.jpg)

**Comment by phpsa** [comment]
update the config file line
`  'UserResource'       => \Phpsa\FilamentAuthentication\Resources\UserResource::class,` to point to your resource
