### ISSUE TITLE
Does not appears Users page 

### ISSUE THREAD

**Issue by Odilbukh** [phpsa/filament-authentication#25]
After command `php artisan migrate:fresh` there is no users page

I have created new user manually in DB. I logged in as the user but the users page does not appears on sidebar. 
Even I have tried to enter bu url ../admin/users but there is error like 403 Forbiddin. It seems I dont have permission. 

So How to create new user with admin permissions and get access to users?

![image](https://user-images.githubusercontent.com/22895615/196684031-bad25e1f-814c-4803-a382-fb21c34e24bb.png)

**Comment by phpsa** [comment]
Do you have a user policy in your laravel installation? 
Filament resources make use of model policies. for the menu item to appear, your user should have viewAny permission on the policy

**Comment by Odilbukh** [comment]
No I dont have other user policy
it's fresh Laravel project yet

**Comment by phpsa** [comment]
Can you confirm if still not working,
It uses the Laravel Policy mapping to determine if allowed to view.

**Comment by Odilbukh** [comment]
You can close the issue
