### ISSUE TITLE
How to selectively hide navigation?

### ISSUE THREAD

**Issue by sirking1991** [phpsa/filament-authentication#31]
Hi,
Is there a way that I can selectively show/hide the navigation group? For example, if a user belongs to admin, then show navigation, otherwise hide it.

Also is it possible to move the navigation to the bottom instead?

<img width="318" alt="Screenshot 2023-02-19 at 5 35 18 PM" src="https://user-images.githubusercontent.com/237772/219940278-89403ece-8bdd-4c31-a5f8-5db4b20a3b79.png">

**Comment by phpsa** [comment]
Fiilament uses policies to determine who should view and not,
assign a policy to each:
https://filamentphp.com/docs/2.x/admin/resources/listing-records#authorization
