### ISSUE TITLE
Role not assigned in User

### ISSUE THREAD

**Issue by moskoweb** [phpsa/filament-authentication#35]
Hello,

I installed the package in a project, and to my surprise, the role assigned to users before installing the package disappeared from all users, the package seems not to have recognized the roles that users had before installing it, and so, the users became permissions.

Needing to assign permissions again to each user, would you like to understand if it's a configuration error, or is it really necessary to reassign the roles?

<img width="818" alt="Captura de Tela 2023-06-22 às 12 05 57" src="https://github.com/phpsa/filament-authentication/assets/6052272/42daea86-3a9e-4111-a752-b2a46a924f0d">

**Comment by phpsa** [comment]
It should not be needed to re-assign, roles - where you using spatie roles for this?

**Comment by moskoweb** [comment]
Hello, I had to reassign, and in a new project, which I'm migrating, the same thing happened, it seems to me that Filament does not recognize the permissions and roles. Tried to find some solution but still nothing.
