### ISSUE TITLE
Asking for a "roles" relationship in the users model

### ISSUE THREAD

**Issue by sivierostein** [phpsa/filament-authentication#4]
I installed filament over a fresh install of laravel Jetstream.
Installed the filament-authentication plugin as oriented in readme...
When I try to access Users resource in the admin panel, I am receiving this message:

Call to undefined relationship [roles] on model [App\Models\User].

Is there any other package I need to install ?  

Thanks in advance.
Rodolfo

PS:  I create a roles function in User.php  returning an empty array [].
And now, the error is:
Call to a member function addEagerConstraints() on array

**Comment by phpsa** [comment]
Spatie roles and permissions has a few steps, adding the trait to the user model should sort. Will update the docs soon

**Comment by phpsa** [comment]
Thank you for the report:
I have updated the documentation now: please follow the steps at:
https://github.com/phpsa/filament-authentication#additional-resources
for both roles&permissions and impersonate
