### ISSUE TITLE
Support for Filament v3

### ISSUE THREAD

**Issue by ehsanquddusi** [phpsa/filament-authentication#45]
Hello,

What are the plans for supporting Filament v3. Is there any roadmap?

**Comment by phpsa** [comment]
Yes it is planned,

**Comment by sprklinginfo** [comment]
any update? couldn't use filament v3 because of this plugin :(

**Comment by calebeso** [comment]
👀

**Comment by phpsa** [comment]
It is in progress- expected cometion early december

**Comment by phpsa** [comment]
Initial version is out for v3 now, some small enhancements are still in progress however
