### ISSUE TITLE
phpsa attach permission dialog bug

### ISSUE THREAD

**Issue by sopingUdb** [phpsa/filament-authentication#49]
dialog closes itself when attach permission or role.
in the browser console there is the following error log:

**select.js?v=3.2.27.0:1 Uncaught (in promise) Could not find Livewire component in DOM tree
(anonymous) @ select.js?v=3.2.27.0:1
await in (anonymous) (async)
(anonymous) @ livewire.js?id=a27c4ca2:815**

https://github.com/phpsa/filament-authentication/assets/89966418/00d7b6a9-f8f5-4252-921e-dc9a68358835

**Comment by sopingUdb** [comment]
strangely when I make "closeModalByClickingAway" true, attach runs fine
<img width="1051" alt="Screen Shot 2024-02-09 at 11 02 14" src="https://github.com/phpsa/filament-authentication/assets/89966418/fdb7c8cd-2bb3-41f7-8de1-9fb2769439cd">

**Comment by phpsa** [comment]
Investigating

**Comment by phpsa** [comment]
I have been unable to replicate this with the current version, can you confirm and if still an issue, let me know
