### ISSUE TITLE
Error on new user

### ISSUE THREAD

**Issue by netbyte-nl** [phpsa/filament-authentication#50]
Getting this error when pressing the "new user" button in the user screen.

Filament\Support\Services\RelationshipJoiner::prepareQueryForNoConstraints(): Argument #1 ($relationship) must be of type Illuminate\Database\Eloquent\Relations\Relation, null given, called in C:\Websites\SDA2.0\SDA\vendor\filament\forms\src\Components\Select.php on line 773

When pressing "view" or "edit" in the user list this error comes: Call to a member function getResults() on null

PHP 8.3.2
10.43.0

**Comment by phpsa** [comment]
Investigating. thank you

**Comment by mrhappyheart** [comment]
same error :)

**Comment by phpsa** [comment]
Have you setup spatie roles and permissions traits in your user model?

**Comment by netbyte-nl** [comment]
Hi @phpsa, yes those are added:

![image](https://github.com/phpsa/filament-authentication/assets/108525105/8ed18306-6503-4249-b552-b4f1dca0df33)

**Comment by phpsa** [comment]
Based on the greyed out, looks like you have not put the use inside the class aswell?![image](https://github.com/phpsa/filament-authentication/assets/952595/27277fc5-aaa8-4c28-9c04-98b3b0e927aa)

**Comment by netbyte-nl** [comment]
I managed to fix most issues with your suggestion above, many thanks for that!
Only one issue remaining and thats when trying to view or edit a role:

![image](https://github.com/phpsa/filament-authentication/assets/108525105/868163f6-059d-4832-969c-4d286ff59032)

**Comment by yukebrillianth** [comment]
> I managed to fix most issues with your suggestion above, many thanks for that! Only one issue remaining and thats when trying to view or edit a role:
> 
> ![image](https://private-user-images.githubusercontent.com/108525105/306910179-868163f6-059d-4832-969c-4d286ff59032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODk2MTEsIm5iZiI6MTcxNTE4OTMxMSwicGF0aCI6Ii8xMDg1MjUxMDUvMzA2OTEwMTc5LTg2ODE2M2Y2LTA1OWQtNDgzMi05NjljLTRkMjg2ZmY1OTAzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQxNzI4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzVlMmM5OWFkZWI4NDY1ODZiNjdjMThjZWJkYjNmMTZiMzlmYjFmM2Q0NmViZTYwNGI2MGM1NmEwOGViNjhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iKXnYwHdS3S900jNjN2FeyyvCzhNsL3JdeO2xixVsDY)

Same Issue

**Comment by phpsa** [comment]
For this issue, is there a repo i can look at - I am unable to replicate this issue.
