### ISSUE TITLE
Undifined Method resources()

### ISSUE THREAD

**Issue by mrhappyheart** [phpsa/filament-authentication#51]
i got this error when i wanted to load resources as document :
`Call to undefined method Phpsa\FilamentAuthentication\FilamentAuthentication::resources() {"exception":"[object] (Error(code: 0): Call to undefined method Phpsa\\FilamentAuthentication\\FilamentAuthentication::resources() at ***/public_html/app/Providers/Filament/AdminPanelProvider.php:37)`

**Comment by phpsa** [comment]
Looks like I forgot to push the readme update somehow - on v4 that changed to

->plugin(FilamentAuthentication::make())
