### ISSUE TITLE
Impersonate Action

### ISSUE THREAD

**Issue by num3r06** [phpsa/filament-authentication#52]
Hi,
Action for impersonate user in UserResource it's not visible.
I'm looking into source code and i found (row 22 FilamentAuthentication class) 
```protected bool $impersonate = false;```
I'm not found configuration fon change this behaviour

**Comment by phpsa** [comment]
![image](https://github.com/phpsa/filament-authentication/assets/952595/a21577dd-77ed-47cc-b22d-b17a8d4d72c1)

Per image - make sure you have latest config file
