### ISSUE TITLE
Error accessing the Dashboard

### ISSUE THREAD

**Issue by stleroux** [phpsa/filament-authentication#8]
I get this error after trying to add the LatestUsers widget to the dashboard.
I even tried to remove the widget and clear the artisan cache but nothing seems to work.
I can access all other pages I have created.

TypeError
Phpsa\FilamentAuthentication\Widgets\LatestUsersWidget::getTableQuery(): Return value must be of type Illuminate\Contracts\Database\Eloquent\Builder, Illuminate\Database\Eloquent\Builder returned (View: C:\laragon\www\Laravel-Test\vendor\filament\filament\resources\views\components\widgets.blade.php)

Thanks

**Comment by phpsa** [comment]
Can you advise PHP & Laravel Version

**Comment by stleroux** [comment]
php v 8.1.5
Laravel 8.83.10
Running on Laragon

The weird thing is, it still gives me the error even after removing the lines for the widget

**Comment by phpsa** [comment]
Can you confirm if the latest version fixes this,
issue around laravel 9 vs 8 was found
also to disable should be a config variable now and not needed to manually add to the config file anymore

**Comment by stleroux** [comment]
Ran composer update on the installation and this resolved the problem.
Thanks for the help
