### ISSUE TITLE
remove LatestUsersWidget ?

### ISSUE THREAD

**Issue by quasiperfect** [phpsa/filament-authentication#9]
hi

i didn't add the class to filament.php widgets register i removed it from filament-authentication.php and it still appears in the admin any idea how i could get rid of it  ?

**Comment by phpsa** [comment]
Publish and look in the config file, under the widgets section you can disable it.

will be updating the documentation shortly

**Comment by quasiperfect** [comment]
i tried that but the widget still appears.

is not added to filament.php config
is set to false in filament-authentication.php config

and somehow is still visible in the dashboard

**Comment by phpsa** [comment]
@quasiperfect --- found the cause (rougue `e` in the config file)
-- please republish from the new version and you should now have the enabled true false control functional
